% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\title{Practice work 2'' - Xu Feiran - 21.M09}
\author{Xu Feiran}
\date{}

\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Practice work 2'' - Xu Feiran - 21.M09},
  pdfauthor={Xu Feiran},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\begin{document}
\maketitle

{
\setcounter{tocdepth}{3}
\tableofcontents
}
\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{szstock}\OtherTok{\textless{}{-}}\FunctionTok{read.csv}\NormalTok{(}\StringTok{"./Datasets{-}master/monthly{-}mean{-}temp.csv"}\NormalTok{)}
\NormalTok{MyData }\OtherTok{\textless{}{-}}\NormalTok{ szstock}\SpecialCharTok{$}\NormalTok{Temperature}
\NormalTok{tsdata }\OtherTok{\textless{}{-}} \FunctionTok{ts}\NormalTok{(MyData, }\AttributeTok{start =}\FunctionTok{c}\NormalTok{(}\DecValTok{1920}\NormalTok{,}\DecValTok{1}\NormalTok{),}\AttributeTok{frequency =} \DecValTok{12}\NormalTok{)}
\FunctionTok{plot.ts}\NormalTok{(tsdata)}
\end{Highlighting}
\end{Shaded}

\includegraphics{in_work2_files/figure-latex/unnamed-chunk-1-1.pdf} Mean
monthly air temperature (Deg. F) Nottingham Castle 1920-1939

Source: Time Series Data Library (citing: O.D. Anderson (1976))

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{MyData.acf }\OtherTok{\textless{}{-}} \FunctionTok{acf}\NormalTok{(MyData)}
\end{Highlighting}
\end{Shaded}

\includegraphics{in_work2_files/figure-latex/unnamed-chunk-2-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{MyData.acf}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Autocorrelations of series 'MyData', by lag
## 
##      0      1      2      3      4      5      6      7      8      9     10 
##  1.000  0.808  0.452 -0.018 -0.464 -0.770 -0.876 -0.756 -0.445 -0.010  0.429 
##     11     12     13     14     15     16     17     18     19     20     21 
##  0.765  0.884  0.770  0.435 -0.011 -0.441 -0.734 -0.844 -0.726 -0.431 -0.015 
##     22     23 
##  0.420  0.732
\end{verbatim}

Autocorrelations of series `MyData', by lag

\begin{verbatim}
 0      1      2      3      4      5      6      7      8      9     10     11     12     13     14     15     16     17     18     19     20     21     22     23 
\end{verbatim}

1.000 0.808 0.452 -0.018 -0.464 -0.770 -0.876 -0.756 -0.445 -0.010 0.429
0.765 0.884 0.770 0.435 -0.011 -0.441 -0.734 -0.844 -0.726 -0.431 -0.015
0.420 0.732

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{MyData.pacf}\OtherTok{\textless{}{-}}\FunctionTok{pacf}\NormalTok{(MyData)}
\end{Highlighting}
\end{Shaded}

\includegraphics{in_work2_files/figure-latex/unnamed-chunk-3-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{MyData.pacf}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Partial autocorrelations of series 'MyData', by lag
## 
##      1      2      3      4      5      6      7      8      9     10     11 
##  0.808 -0.577 -0.552 -0.364 -0.215 -0.250 -0.224 -0.145  0.050  0.122  0.223 
##     12     13     14     15     16     17     18     19     20     21     22 
##  0.084  0.099 -0.055 -0.056  0.012  0.117 -0.078 -0.009 -0.098  0.035  0.145 
##     23 
##  0.007
\end{verbatim}

Here are the ACF and PACF of this time series. We can see straight away
that this time series is unstable.

Using diff function in R library forecast to create the difference
series.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{diff1 }\OtherTok{\textless{}{-}} \FunctionTok{diff}\NormalTok{(tsdata,}\AttributeTok{lag =} \DecValTok{1}\NormalTok{)}
\FunctionTok{acf}\NormalTok{(diff1)}
\end{Highlighting}
\end{Shaded}

\includegraphics{in_work2_files/figure-latex/unnamed-chunk-4-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{diff2 }\OtherTok{\textless{}{-}} \FunctionTok{diff}\NormalTok{(tsdata,}\AttributeTok{lag =} \DecValTok{2}\NormalTok{)}
\FunctionTok{acf}\NormalTok{(diff2)}
\end{Highlighting}
\end{Shaded}

\includegraphics{in_work2_files/figure-latex/unnamed-chunk-5-1.pdf} ADF
test. H0: There exist the unit root.(not stationary series) H1: There
doesn't exist the unit root.(stationary series)

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(tseries)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Registered S3 method overwritten by 'quantmod':
##   method            from
##   as.zoo.data.frame zoo
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{adf.test}\NormalTok{(tsdata)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in adf.test(tsdata): p-value smaller than printed p-value
\end{verbatim}

\begin{verbatim}
## 
##  Augmented Dickey-Fuller Test
## 
## data:  tsdata
## Dickey-Fuller = -13, Lag order = 6, p-value = 0.01
## alternative hypothesis: stationary
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{adf.test}\NormalTok{(diff1[}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in adf.test(diff1[-1]): p-value smaller than printed p-value
\end{verbatim}

\begin{verbatim}
## 
##  Augmented Dickey-Fuller Test
## 
## data:  diff1[-1]
## Dickey-Fuller = -13.933, Lag order = 6, p-value = 0.01
## alternative hypothesis: stationary
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{adf.test}\NormalTok{(diff2[}\SpecialCharTok{{-}}\DecValTok{2}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in adf.test(diff2[-2]): p-value smaller than printed p-value
\end{verbatim}

\begin{verbatim}
## 
##  Augmented Dickey-Fuller Test
## 
## data:  diff2[-2]
## Dickey-Fuller = -14.031, Lag order = 6, p-value = 0.01
## alternative hypothesis: stationary
\end{verbatim}

This result show that we shoud reject the null hypothesis, which means
the process is stationary.

We can use ndiffs function to find the order.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(forecast)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: 程辑包'forecast'是用R版本4.1.2 来建造的
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ndiffs}\NormalTok{(tsdata)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0
\end{verbatim}

The result show us the order of stationary is 0 . As stated above, this
time series is inherently stable.

From the ACF and PACF figures, i think we chose p = 3 and q= 2 will be
good. And as i told before, d=0. So i construct ARIMA(3,0,2) model.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fit\_model }\OtherTok{\textless{}{-}} \FunctionTok{Arima}\NormalTok{(diff1,}\AttributeTok{order =} \FunctionTok{c}\NormalTok{(}\DecValTok{3}\NormalTok{,}\DecValTok{0}\NormalTok{,}\DecValTok{2}\NormalTok{))}
\NormalTok{fit\_model}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Series: diff1 
## ARIMA(3,0,2) with non-zero mean 
## 
## Coefficients:
##          ar1      ar2      ar3      ma1     ma2    mean
##       1.3337  -0.3335  -0.3643  -1.7428  0.7778  0.0002
## s.e.  0.0661   0.1117   0.0650   0.0390  0.0417  0.0181
## 
## sigma^2 estimated as 8.273:  log likelihood=-591.92
## AIC=1197.84   AICc=1198.33   BIC=1222.18
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{checkresiduals}\NormalTok{(fit\_model)}
\end{Highlighting}
\end{Shaded}

\includegraphics{in_work2_files/figure-latex/unnamed-chunk-9-1.pdf}

\begin{verbatim}
## 
##  Ljung-Box test
## 
## data:  Residuals from ARIMA(3,0,2) with non-zero mean
## Q* = 83.242, df = 18, p-value = 2.307e-10
## 
## Model df: 6.   Total lags used: 24
\end{verbatim}

There hasn't autocorrelation for low order members.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(}\FunctionTok{decompose}\NormalTok{(tsdata,}\AttributeTok{type =} \StringTok{"additive"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{in_work2_files/figure-latex/unnamed-chunk-10-1.pdf} I
tried to use function decompose to find the seasonal component, and we
can easily saw there has seasonal component in my time series, and the
seasonal cycle is equal to 12. And here is the Seasonal Difference.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{seas\_diff }\OtherTok{\textless{}{-}} \FunctionTok{diff}\NormalTok{(tsdata, }\AttributeTok{lag =} \DecValTok{12}\NormalTok{)}
\FunctionTok{plot}\NormalTok{(seas\_diff)}
\end{Highlighting}
\end{Shaded}

\includegraphics{in_work2_files/figure-latex/unnamed-chunk-11-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{seas\_diff\_fit }\OtherTok{\textless{}{-}} \FunctionTok{auto.arima}\NormalTok{(tsdata,}\AttributeTok{seasonal =}\NormalTok{ T)}
\NormalTok{seas\_diff\_fit}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Series: tsdata 
## ARIMA(1,0,2)(1,1,2)[12] with drift 
## 
## Coefficients:
##          ar1     ma1     ma2     sar1     sma1     sma2  drift
##       0.1565  0.0921  0.1114  -0.5254  -0.5021  -0.2326  0.004
## s.e.  0.3647  0.3600  0.1135   0.1928   0.2087   0.1894  0.004
## 
## sigma^2 estimated as 5.205:  log likelihood=-516.21
## AIC=1048.42   AICc=1049.08   BIC=1075.86
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{checkresiduals}\NormalTok{(seas\_diff\_fit)}
\end{Highlighting}
\end{Shaded}

\includegraphics{in_work2_files/figure-latex/unnamed-chunk-13-1.pdf}

\begin{verbatim}
## 
##  Ljung-Box test
## 
## data:  Residuals from ARIMA(1,0,2)(1,1,2)[12] with drift
## Q* = 17.926, df = 17, p-value = 0.3935
## 
## Model df: 7.   Total lags used: 24
\end{verbatim}

In this case, the p-value = 0.3935 is greater than 0.05, so we have to
reject the H0, that means the residuals of this model is white-noise.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{seas\_diff\_fit.residual }\OtherTok{\textless{}{-}} \FunctionTok{residuals}\NormalTok{(seas\_diff\_fit)}
\FunctionTok{shapiro.test}\NormalTok{(seas\_diff\_fit.residual)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Shapiro-Wilk normality test
## 
## data:  seas_diff_fit.residual
## W = 0.9924, p-value = 0.2543
\end{verbatim}

The p-value=0.2543 is greater than 0.05, that mean the H0 can not be
rejected, so the residuals is normality.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{  force\_best }\OtherTok{\textless{}{-}} \FunctionTok{forecast}\NormalTok{(}\FunctionTok{Arima}\NormalTok{(tsdata,}\AttributeTok{order=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{0}\NormalTok{,}\DecValTok{2}\NormalTok{),}\AttributeTok{seasonal=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{),}\AttributeTok{lambda=}\DecValTok{0}\NormalTok{),}\AttributeTok{h=}\DecValTok{216}\NormalTok{)}
\NormalTok{  force\_intuition }\OtherTok{\textless{}{-}} \FunctionTok{forecast}\NormalTok{(}\FunctionTok{Arima}\NormalTok{(tsdata,}\AttributeTok{order=}\FunctionTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{0}\NormalTok{,}\DecValTok{2}\NormalTok{),}\AttributeTok{seasonal=}\FunctionTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{),}\AttributeTok{lambda=}\DecValTok{0}\NormalTok{),}\AttributeTok{h=}\DecValTok{216}\NormalTok{)}
  \FunctionTok{autoplot}\NormalTok{(force\_best)}
\end{Highlighting}
\end{Shaded}

\includegraphics{in_work2_files/figure-latex/unnamed-chunk-15-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
  \FunctionTok{autoplot}\NormalTok{(force\_intuition)}
\end{Highlighting}
\end{Shaded}

\includegraphics{in_work2_files/figure-latex/unnamed-chunk-15-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(force\_best)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Forecast method: ARIMA(1,0,2)(1,1,2)[12]
## 
## Model Information:
## Series: tsdata 
## ARIMA(1,0,2)(1,1,2)[12] 
## Box Cox transformation: lambda= 0 
## 
## Coefficients:
##          ar1     ma1     ma2     sar1     sma1     sma2
##       0.0957  0.1543  0.1347  -0.5334  -0.5079  -0.2230
## s.e.  0.3597  0.3543  0.1093   0.1746   0.1909   0.1748
## 
## sigma^2 estimated as 0.002524:  log likelihood=353.2
## AIC=-692.41   AICc=-691.9   BIC=-668.4
## 
## Error measures:
##                   ME     RMSE      MAE          MPE     MAPE      MASE
## Training set 0.12794 2.197483 1.719495 -0.003441257 3.678136 0.6378863
##                     ACF1
## Training set 0.008818547
## 
## Forecasts:
##          Point Forecast    Lo 80    Hi 80    Lo 95    Hi 95
## Jan 1940       40.20586 37.69857 42.87990 36.43522 44.36672
## Feb 1940       39.08098 36.57131 41.76287 35.30868 43.25630
## Mar 1940       43.10105 40.30170 46.09484 38.89419 47.76294
## Apr 1940       46.31372 43.30541 49.53102 41.79283 51.32366
## May 1940       52.53460 49.12220 56.18405 47.40645 58.21748
## Jun 1940       58.89013 55.06491 62.98108 53.14159 65.26052
## Jul 1940       61.68303 57.67640 65.96800 55.66186 68.35554
## Aug 1940       61.29453 57.31313 65.55250 55.31128 67.92500
## Sep 1940       57.08210 53.37432 61.04745 51.51005 63.25690
## Oct 1940       50.07378 46.82123 53.55228 45.18585 55.49047
## Nov 1940       43.78345 40.93948 46.82497 39.50954 48.51968
## Dec 1940       39.36883 36.81162 42.10368 35.52586 43.62751
## Jan 1941       39.66164 37.08347 42.41905 35.78722 43.95551
## Feb 1941       39.74524 37.16152 42.50860 35.86247 44.04839
## Mar 1941       42.40320 39.64664 45.35143 38.26070 46.99422
## Apr 1941       46.81088 43.76778 50.06556 42.23777 51.87911
## May 1941       52.53659 49.12127 56.18937 47.40413 58.22475
## Jun 1941       58.58991 54.78107 62.66356 52.86607 64.93346
## Jul 1941       61.56537 57.56310 65.84591 55.55085 68.23108
## Aug 1941       61.55983 57.55793 65.83999 55.54586 68.22495
## Sep 1941       57.41835 53.68568 61.41055 51.80897 63.63506
## Oct 1941       48.92638 45.74575 52.32815 44.14661 54.22366
## Nov 1941       44.27059 41.39263 47.34865 39.94566 49.06379
## Dec 1941       38.78879 36.26719 41.48571 34.99939 42.98847
## Jan 1942       39.90772 37.21778 42.79207 35.86800 44.40241
## Feb 1942       39.44270 36.77833 42.30010 35.44154 43.89558
## Mar 1942       42.77955 39.88725 45.88158 38.43617 47.61374
## Apr 1942       46.54560 43.39865 49.92075 41.81982 51.80542
## May 1942       52.53559 48.98366 56.34509 47.20165 58.47229
## Jun 1942       58.74987 54.77779 63.00998 52.78499 65.38880
## Jul 1942       61.62811 57.46143 66.09692 55.37100 68.59229
## Aug 1942       61.41817 57.26569 65.87177 55.18238 68.35864
## Sep 1942       57.23874 53.36883 61.38928 51.42729 63.70692
## Oct 1942       49.53511 46.18604 53.12703 44.50580 55.13274
## Nov 1942       44.01007 41.03455 47.20136 39.54172 48.98336
## Dec 1942       39.09712 36.45376 41.93215 35.12758 43.51522
## Jan 1943       39.77627 37.07282 42.67686 35.71689 44.29701
## Feb 1943       39.60379 36.91119 42.49282 35.56072 44.10654
## Mar 1943       42.57839 39.68316 45.68485 38.23109 47.42003
## Apr 1943       46.68692 43.51232 50.09313 41.92013 51.99575
## May 1943       52.53613 48.96380 56.36909 47.17212 58.51008
## Jun 1943       58.66449 54.67544 62.94457 52.67477 65.33530
## Jul 1943       61.59463 57.40635 66.08849 55.30575 68.59864
## Aug 1943       61.49370 57.31227 65.98019 55.21511 68.48622
## Sep 1943       57.33448 53.43587 61.51752 51.48056 63.85406
## Oct 1943       49.20947 45.86334 52.79972 44.18512 54.80514
## Nov 1943       44.14884 41.14683 47.36988 39.64119 49.16907
## Dec 1943       38.93235 36.28504 41.77280 34.95731 43.35939
## Jan 1944       39.84633 37.08985 42.80767 35.70871 44.46339
## Feb 1944       39.51778 36.78115 42.45804 35.41003 44.10206
## Mar 1944       42.68557 39.72831 45.86297 38.24669 47.63963
## Apr 1944       46.61149 43.38222 50.08113 41.76433 52.02120
## May 1944       52.53584 48.89614 56.44648 47.07261 58.63314
## Jun 1944       58.71001 54.64256 63.08024 52.60472 65.52389
## Jul 1944       61.61249 57.34395 66.19876 55.20536 68.76322
## Aug 1944       61.45340 57.19588 66.02784 55.06282 68.58567
## Sep 1944       57.28339 53.31477 61.54742 51.32645 63.93169
## Oct 1944       49.38290 45.96163 53.05884 44.24754 55.11427
## Nov 1944       44.07477 41.02125 47.35558 39.49140 49.19007
## Dec 1944       39.02015 36.31682 41.92471 34.96242 43.54882
## Jan 1945       39.80894 37.02443 42.80288 35.63012 44.47787
## Feb 1945       39.56364 36.79464 42.54102 35.40815 44.20681
## Mar 1945       42.62837 39.64416 45.83721 38.14994 47.63252
## Apr 1945       46.65171 43.38584 50.16341 41.75058 52.12817
## May 1945       52.53599 48.85819 56.49064 47.01668 58.70322
## Jun 1945       58.68573 54.57741 63.10329 52.52034 65.57487
## Jul 1945       61.60296 57.29043 66.24013 55.13110 68.83457
## Aug 1945       61.47489 57.17132 66.10241 55.01648 68.69146
## Sep 1945       57.31064 53.29859 61.62469 51.28971 64.03836
## Oct 1945       49.29031 45.83973 53.00064 44.11198 55.07653
## Nov 1945       44.11426 41.02603 47.43496 39.47972 49.29286
## Dec 1945       38.97329 36.24495 41.90700 34.87885 43.54838
## Jan 1946       39.82888 37.00476 42.86854 35.59174 44.57045
## Feb 1946       39.53917 36.73338 42.55928 35.32960 44.25032
## Mar 1946       42.65887 39.63074 45.91838 38.11574 47.74351
## Apr 1946       46.63025 43.32019 50.19322 41.66416 52.18826
## May 1946       52.53591 48.80664 56.55013 46.94087 58.79784
## Jun 1946       58.69868 54.53195 63.18379 52.44731 65.69517
## Jul 1946       61.60804 57.23479 66.31545 55.04683 68.95131
## Aug 1946       61.46343 57.10044 66.15979 54.91761 68.78946
## Sep 1946       57.29610 53.22893 61.67404 51.19411 64.12541
## Oct 1946       49.33968 45.83730 53.10968 44.08504 55.22064
## Nov 1946       44.09319 40.96323 47.46231 39.39730 49.34880
## Dec 1946       38.99828 36.22998 41.97810 34.84499 43.64661
## Jan 1947       39.81825 36.96165 42.89561 35.53338 44.61981
## Feb 1947       39.55222 36.71286 42.61118 35.29325 44.32514
## Mar 1947       42.64260 39.58057 45.94150 38.04967 47.78993
## Apr 1947       46.64169 43.29250 50.24999 41.61802 52.27177
## May 1947       52.53596 48.76351 56.60024 46.87743 58.87752
## Jun 1947       58.69177 54.47730 63.23228 52.37021 65.77640
## Jul 1947       61.60533 57.18165 66.37124 54.96996 69.04165
## Aug 1947       61.46954 57.05561 66.22495 54.84880 68.88947
## Sep 1947       57.30385 53.18904 61.73700 51.13179 64.22095
## Oct 1947       49.31334 45.77230 53.12832 44.00191 55.26591
## Nov 1947       44.10443 40.93743 47.51644 39.35404 49.42823
## Dec 1947       38.98495 36.18556 42.00090 34.78597 43.69078
## Jan 1948       39.82392 36.93186 42.94245 35.48691 44.69098
## Feb 1948       39.54526 36.67144 42.64430 35.23566 44.38196
## Mar 1948       42.65128 39.55087 45.99473 38.00191 47.86948
## Apr 1948       46.63559 43.24554 50.29138 41.55188 52.34127
## May 1948       52.53593 48.71697 56.65426 46.80903 58.96350
## Jun 1948       58.69546 54.42875 63.29663 52.29711 65.87661
## Jul 1948       61.60678 57.12844 66.43618 54.89107 69.14412
## Aug 1948       61.46628 56.99815 66.28467 54.76589 68.98644
## Sep 1948       57.29972 53.13447 61.79149 51.05352 64.31011
## Oct 1948       49.32739 45.74167 53.19420 43.95025 55.36240
## Nov 1948       44.09844 40.89282 47.55534 39.29130 49.49370
## Dec 1948       38.99206 36.15764 42.04867 34.74157 43.76258
## Jan 1949       39.82089 36.89567 42.97804 35.43517 44.74943
## Feb 1949       39.54897 36.64184 42.68675 35.19043 44.44735
## Mar 1949       42.64665 39.51100 46.03115 37.94552 47.93021
## Apr 1949       46.63884 43.20965 50.34018 41.49762 52.41702
## May 1949       52.53594 48.67316 56.70529 46.74466 59.04472
## Jun 1949       58.69349 54.37796 63.35150 52.22343 65.96514
## Jul 1949       61.60601 57.07633 66.49516 54.81489 69.23849
## Aug 1949       61.46802 56.94849 66.34623 54.69211 69.08341
## Sep 1949       57.30193 53.08872 61.84950 50.98526 64.40117
## Oct 1949       49.31989 45.69358 53.23400 43.88313 55.43023
## Nov 1949       44.10163 40.85899 47.60161 39.24010 49.56547
## Dec 1949       38.98827 36.12160 42.08244 34.69041 43.81860
## Jan 1950       39.82251 36.86357 43.01894 35.38727 44.81362
## Feb 1950       39.54699 36.60662 42.72354 35.13965 44.50713
## Mar 1950       42.64912 39.47727 46.07581 37.89483 47.99987
## Apr 1950       46.63711 43.16867 50.38423 41.43825 52.48821
## May 1950       52.53594 48.62880 56.75701 46.67952 59.12711
## Jun 1950       58.69454 54.32938 63.41043 52.15159 66.05837
## Jul 1950       61.60642 57.02470 66.55627 54.73887 69.33557
## Aug 1950       61.46709 56.89573 66.40574 54.61507 69.17877
## Sep 1950       57.30075 53.03924 61.90465 50.91317 64.48971
## Oct 1950       49.32389 45.65563 53.28688 43.82553 55.51208
## Nov 1950       44.09993 40.82018 47.64319 39.18391 49.63271
## Dec 1950       38.99029 36.09055 42.12301 34.64386 43.88202
## Jan 1951       39.82165 36.82994 43.05637 35.33831 44.87377
## Feb 1951       39.54805 36.57504 42.76272 35.09279 44.56893
## Mar 1951       42.64780 39.44096 46.11538 37.84216 48.06372
## Apr 1951       46.63803 43.13115 50.43006 41.38275 52.56070
## May 1951       52.53594 48.58557 56.80751 46.61607 59.20759
## Jun 1951       58.69398 54.28056 63.46624 52.08020 66.14765
## Jul 1951       61.60620 56.97380 66.61525 54.66427 69.42970
## Aug 1951       61.46759 56.84561 66.46537 54.54128 69.27348
## Sep 1951       57.30138 52.99267 61.96041 50.84452 64.57820
## Oct 1951       49.32176 45.61307 53.33199 43.76407 55.58523
## Nov 1951       44.10084 40.78473 47.68657 39.13145 49.70129
## Dec 1951       38.98921 36.05747 42.15933 34.59582 43.94053
## Jan 1952       39.82210 36.79775 43.09502 35.29088 44.93513
## Feb 1952       39.54749 36.54214 42.80000 35.04479 44.62870
## Mar 1952       42.64850 39.40670 46.15700 37.79156 48.12965
## Apr 1952       46.63754 43.09251 50.47420 41.32630 52.63137
## May 1952       52.53594 48.54256 56.85784 46.55298 59.28783
## Jun 1952       58.69428 54.23279 63.52279 52.00998 66.23764
## Jul 1952       61.60632 56.92348 66.67439 54.59039 69.52393
## Aug 1952       61.46732 56.79505 66.52397 54.46722 69.36707
## Sep 1952       57.30104 52.94545 62.01494 50.77541 64.66534
## Oct 1952       49.32290 45.57375 53.38047 43.70584 55.66185
## Nov 1952       44.10035 40.74818 47.72829 39.07806 49.76811
## Dec 1952       38.98979 36.02608 42.19730 34.54950 44.00073
## Jan 1953       39.82186 36.76540 43.13242 35.24354 44.99492
## Feb 1953       39.54779 36.51054 42.83770 34.99831 44.68865
## Mar 1953       42.64813 39.37198 46.19688 37.74084 48.19349
## Apr 1953       46.63780 43.05517 50.51854 41.27143 52.70195
## May 1953       52.53594 48.50023 56.90747 46.49090 59.36700
## Jun 1953       58.69412 54.18534 63.57807 51.94049 66.32590
## Jul 1953       61.60625 56.87377 66.73252 54.51754 69.61669
## Aug 1953       61.46746 56.74565 66.58218 54.39472 69.45985
## Sep 1953       57.30122 52.89945 62.06927 50.70786 64.75189
## Oct 1953       49.32229 45.53344 53.42641 43.64703 55.73549
## Nov 1953       44.10061 40.71288 47.77023 39.02618 49.83485
## Dec 1953       38.98948 35.99438 42.23380 34.50316 44.05914
## Jan 1954       39.82199 36.73371 43.16990 35.19704 45.05466
## Feb 1954       39.54763 36.47882 42.87459 34.95190 44.74763
## Mar 1954       42.64833 39.33813 46.23706 37.69113 48.25750
## Apr 1954       46.63766 43.01783 50.56210 41.21676 52.77154
## May 1954       52.53594 48.45830 56.95670 46.42945 59.44557
## Jun 1954       58.69420 54.13858 63.63317 51.87191 66.41378
## Jul 1954       61.60629 56.82464 66.79029 54.44551 69.70886
## Aug 1954       61.46739 56.69652 66.63971 54.32276 69.55170
## Sep 1954       57.30112 52.85363 62.12286 50.64076 64.83748
## Oct 1954       49.32261 45.49438 53.47298 43.58962 55.80962
## Nov 1954       44.10047 40.67756 47.81141 38.97448 49.90065
## Dec 1954       38.98964 35.96342 42.27052 34.45770 44.11763
## Jan 1955       39.82192 36.70224 43.20678 35.15096 45.11357
## Feb 1955       39.54771 36.44773 42.91136 34.90631 44.80627
## Mar 1955       42.64822 39.30443 46.27648 37.64180 48.32050
## Apr 1955       46.63774 42.98114 50.60542 41.16298 52.84065
## May 1955       52.53594 48.41690 57.00540 46.36880 59.52332
## Jun 1955       58.69416 54.09229 63.68753 51.80411 66.50060
## Jul 1955       61.60627 56.77608 66.84739 54.37437 69.80002
## Aug 1955       61.46743 56.64812 66.69673 54.25183 69.64272
## Sep 1955       57.30118 52.80852 62.17604 50.57465 64.92234
## Oct 1955       49.32244 45.45535 53.51852 43.53253 55.88242
## Nov 1955       44.10055 40.64288 47.85237 38.92363 49.96600
## Dec 1955       38.98956 35.93261 42.30657 34.41261 44.17524
## Jan 1956       39.82196 36.67120 43.24343 35.10549 45.17209
## Feb 1956       39.54767 36.41684 42.94765 34.86110 44.86427
## Mar 1956       42.64828 39.27123 46.31573 37.59316 48.38315
## Apr 1956       46.63770 42.94474 50.64822 41.10970 52.90904
## May 1956       52.53594 48.37594 57.05367 46.30882 59.60042
## Jun 1956       58.69418 54.04655 63.74148 51.73712 66.58676
## Jul 1956       61.60628 56.72805 66.90400 54.30404 69.89044
## Aug 1956       61.46741 56.60018 66.75318 54.18163 69.73289
## Sep 1956       57.30115 52.76382 62.22865 50.50920 65.00640
## Oct 1956       49.32253 45.41698 53.56393 43.47630 55.95491
## Nov 1956       44.10051 40.60846 47.89285 38.87324 50.03068
## Dec 1956       38.98960 35.90225 42.34244 34.36814 44.23251
## Jan 1957       39.82194 36.64045 43.27967 35.06050 45.23001
## Feb 1957       39.54769 36.38637 42.98367 34.81649 44.92181
## Mar 1957       42.64825 39.23832 46.35450 37.54501 48.44513
## Apr 1957       46.63772 42.90881 50.69068 41.05710 52.97688
## May 1957       52.53594 48.33544 57.10147 46.24954 59.67681
## Jun 1957       58.69417 54.00129 63.79487 51.67088 66.67208
## Jul 1957       61.60627 56.68056 66.96005 54.23453 69.98001
## Aug 1957       61.46742 56.55281 66.80912 54.11229 69.82228
## Sep 1957       57.30116 52.71966 62.28081 50.44456 65.08973
## Oct 1957       49.32248 45.37892 53.60876 43.42061 56.02657
## Nov 1957       44.10053 40.57448 47.93300 38.82350 50.09482
## Dec 1957       38.98958 35.87218 42.37789 34.32413 44.28917
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(force\_intuition)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Forecast method: ARIMA(2,0,2)(2,2,2)[12]
## 
## Model Information:
## Series: tsdata 
## ARIMA(2,0,2)(2,2,2)[12] 
## Box Cox transformation: lambda= 0 
## 
## Coefficients:
##          ar1      ar2      ma1     ma2     sar1    sar2     sma1    sma2
##       0.3246  -0.1344  -0.0467  0.1846  -0.0656  0.2504  -1.9570  0.9994
## s.e.  1.0343   0.4608   1.0301  0.2521   0.0791  0.0818   0.5309  0.5422
## 
## sigma^2 estimated as 0.002528:  log likelihood=300.05
## AIC=-582.1   AICc=-581.23   BIC=-551.73
## 
## Error measures:
##                     ME     RMSE      MAE       MPE     MAPE      MASE
## Training set 0.2126706 2.124374 1.649093 0.3716462 3.519524 0.6117689
##                    ACF1
## Training set 0.00803251
## 
## Forecasts:
##          Point Forecast    Lo 80    Hi 80    Lo 95    Hi 95
## Jan 1940       40.05138 37.43865 42.84644 36.12528 44.40417
## Feb 1940       39.42600 36.75998 42.28537 35.42245 43.88204
## Mar 1940       43.72369 40.74109 46.92465 39.24546 48.71293
## Apr 1940       46.80248 43.60976 50.22894 42.00877 52.14321
## May 1940       52.53292 48.94887 56.37939 47.15166 58.52832
## Jun 1940       59.93029 55.84149 64.31848 53.79117 66.77005
## Jul 1940       61.74781 57.53500 66.26908 55.42251 68.79501
## Aug 1940       62.47038 58.20828 67.04456 56.07106 69.60005
## Sep 1940       58.17712 54.20793 62.43695 52.21759 64.81681
## Oct 1940       49.87816 46.47517 53.53032 44.76876 55.57069
## Nov 1940       45.89341 42.76228 49.25379 41.19219 51.13116
## Dec 1940       39.26700 36.58797 42.14219 35.24458 43.74849
## Jan 1941       39.58874 36.88242 42.49365 35.52549 44.11673
## Feb 1941       39.93785 37.20724 42.86885 35.83815 44.50653
## Mar 1941       42.80908 39.88205 45.95094 38.41448 47.70643
## Apr 1941       47.21470 43.98644 50.67989 42.36784 52.61604
## May 1941       52.66388 49.06303 56.52900 47.25762 58.68861
## Jun 1941       59.69438 55.61283 64.07549 53.56640 66.52340
## Jul 1941       61.75750 57.53488 66.29002 55.41773 68.82254
## Aug 1941       62.69921 58.41221 67.30085 56.26277 69.87198
## Sep 1941       58.57567 54.57061 62.87467 52.56253 65.27671
## Oct 1941       48.73294 45.40087 52.30956 43.73022 54.30797
## Nov 1941       45.94284 42.80155 49.31467 41.22656 51.19866
## Dec 1941       38.82939 36.17452 41.67910 34.84341 43.27135
## Jan 1942       40.03997 37.09671 43.21675 35.62726 44.99922
## Feb 1942       39.89914 36.95103 43.08247 35.47962 44.86918
## Mar 1942       43.50956 40.29046 46.98586 38.68393 48.93716
## Apr 1942       46.99053 43.51388 50.74497 41.77881 52.85240
## May 1942       52.83802 48.92866 57.05974 46.97765 59.42946
## Jun 1942       60.35378 55.88833 65.17601 53.65980 67.88281
## Jul 1942       61.81724 57.24351 66.75640 54.96095 69.52884
## Aug 1942       62.76692 58.12293 67.78197 55.80530 70.59700
## Sep 1942       58.63644 54.29806 63.32146 52.13294 65.95124
## Oct 1942       49.70131 46.02401 53.67241 44.18882 55.90146
## Nov 1942       46.05990 42.65207 49.74001 40.95135 51.80572
## Dec 1942       39.24570 36.34217 42.38120 34.89313 44.14121
## Jan 1943       40.15278 37.13536 43.41537 35.63094 45.24846
## Feb 1943       40.39535 37.35597 43.68203 35.84071 45.52880
## Mar 1943       43.54391 40.26660 47.08797 38.63276 49.07939
## Apr 1943       47.16020 43.61071 50.99859 41.84118 53.15541
## May 1943       53.00935 49.01960 57.32382 47.03059 59.74815
## Jun 1943       60.40338 55.85712 65.31967 53.59067 68.08216
## Jul 1943       61.61160 56.97440 66.62622 54.66262 69.44397
## Aug 1943       62.73319 58.01158 67.83910 55.65771 70.70814
## Sep 1943       58.82582 54.39830 63.61371 52.19105 66.30405
## Oct 1943       49.43173 45.71125 53.45501 43.85648 55.71573
## Nov 1943       46.36228 42.87293 50.13563 41.13337 52.25590
## Dec 1943       39.12386 36.17961 42.30771 34.71180 44.09671
## Jan 1944       40.52060 37.33854 43.97384 35.75650 45.91946
## Feb 1944       40.72035 37.51225 44.20282 35.91759 46.16532
## Mar 1944       44.03253 40.56062 47.80162 38.83494 49.92575
## Apr 1944       47.14457 43.42728 51.18006 41.57962 53.45433
## May 1944       53.19225 48.99806 57.74547 46.91337 60.31151
## Jun 1944       60.71990 55.93214 65.91748 53.55242 68.84667
## Jul 1944       61.43642 56.59216 66.69533 54.18436 69.65908
## Aug 1944       62.66568 57.72450 68.02981 55.26852 71.05287
## Sep 1944       58.92186 54.27589 63.96553 51.96664 66.80798
## Oct 1944       49.77652 45.85165 54.03735 43.90082 56.43861
## Nov 1944       46.67157 42.99170 50.66642 41.16263 52.91778
## Dec 1944       39.25201 36.15770 42.61113 34.61967 44.50419
## Jan 1945       40.78778 37.46134 44.40961 35.81169 46.45532
## Feb 1945       41.19693 37.82807 44.86582 36.15769 46.93849
## Mar 1945       44.32465 40.69754 48.27503 38.89920 50.50682
## Apr 1945       47.23993 43.37425 51.45013 41.45763 53.82872
## May 1945       53.37421 49.00652 58.13117 46.84100 60.81865
## Jun 1945       60.86535 55.88463 66.28996 53.41518 69.35464
## Jul 1945       61.19388 56.18628 66.64777 53.70350 69.72899
## Aug 1945       62.57511 57.45449 68.15211 54.91566 71.30287
## Sep 1945       59.05657 54.22388 64.31997 51.82781 67.29357
## Oct 1945       49.76905 45.69637 54.20470 43.67712 56.71066
## Nov 1945       47.02966 43.18141 51.22085 41.27342 53.58869
## Dec 1945       39.22859 36.01953 42.72355 34.42843 44.69800
## Jan 1946       41.12847 37.59978 44.98832 35.85606 47.17615
## Feb 1946       41.62386 38.03934 45.54616 36.26851 47.76998
## Mar 1946       44.74806 40.89085 48.96912 38.98543 51.36249
## Apr 1946       47.28156 43.20595 51.74162 41.19265 54.27051
## May 1946       53.55968 48.94284 58.61202 46.66219 61.47673
## Jun 1946       61.08982 55.82388 66.85250 53.22257 70.11998
## Jul 1946       60.96413 55.70902 66.71495 53.11307 69.97571
## Aug 1946       62.47776 57.09218 68.37136 54.43177 71.71308
## Sep 1946       59.16544 54.06539 64.74659 51.54603 67.91114
## Oct 1946       49.93944 45.63467 54.65029 43.50817 57.32137
## Nov 1946       47.38865 43.30412 51.85844 41.28641 54.39283
## Dec 1946       39.27781 35.89356 42.98115 34.22173 45.08090
## Jan 1947       41.44082 37.69101 45.56368 35.84535 47.90974
## Feb 1947       42.09704 38.27302 46.30314 36.39139 48.69726
## Mar 1947       45.11554 41.01328 49.62813 38.99489 52.19690
## Apr 1947       47.35465 43.04877 52.09122 40.93020 54.78748
## May 1947       53.74520 48.85817 59.12105 46.45367 62.18122
## Jun 1947       61.26645 55.69551 67.39463 52.95452 70.88306
## Jul 1947       60.71762 55.19658 66.79089 52.48014 70.24807
## Aug 1947       62.37523 56.70347 68.61431 53.91287 72.16588
## Sep 1947       59.28591 53.89507 65.21597 51.24269 68.59163
## Oct 1947       50.00970 45.46234 55.01191 43.22497 57.85939
## Nov 1947       47.76240 43.41986 52.53924 41.28325 55.25841
## Dec 1947       39.28427 35.71410 43.21132 33.95745 45.44669
## Jan 1948       41.77585 37.76152 46.21695 35.79504 48.75597
## Feb 1948       42.55869 38.45102 47.10519 36.43955 49.70540
## Mar 1948       45.52299 41.12428 50.39220 38.97050 53.17722
## Apr 1948       47.41225 42.83097 52.48356 40.58780 55.38417
## May 1948       53.93213 48.72077 59.70090 46.16910 63.00045
## Jun 1948       61.46663 55.52722 68.04134 52.61906 71.80186
## Jul 1948       60.47619 54.63249 66.94496 51.77119 70.64489
## Aug 1948       62.27150 56.25432 68.93230 53.30808 72.74207
## Sep 1948       59.39931 53.65967 65.75288 50.84933 69.38692
## Oct 1948       50.13143 45.28733 55.49367 42.91548 58.56070
## Nov 1948       48.13783 43.48696 53.28610 41.20970 56.23072
## Dec 1948       39.31175 35.51551 43.51376 33.65664 45.91705
## Jan 1949       42.10433 37.79616 46.90356 35.69697 49.66176
## Feb 1949       43.03724 38.61323 47.96812 36.45847 50.80311
## Mar 1949       45.91640 41.19090 51.18403 38.88953 54.21294
## Apr 1949       47.47884 42.59252 52.92574 40.21284 56.05773
## May 1949       54.11951 48.54967 60.32834 45.83711 63.89846
## Jun 1949       61.65369 55.30843 68.72690 52.21825 72.79404
## Jul 1949       60.23108 54.03224 67.14109 51.01336 71.11438
## Aug 1949       62.16670 55.76865 69.29877 52.65275 73.39975
## Sep 1949       59.51627 53.39101 66.34425 50.40796 70.27039
## Oct 1949       50.22477 45.05577 55.98679 42.53842 59.29998
## Nov 1949       48.51935 43.52658 54.08484 41.09502 57.28498
## Dec 1949       39.32713 35.28251 43.83541 33.31263 46.42754
## Jan 1950       42.44116 37.80368 47.64754 35.55753 50.65740
## Feb 1950       43.51605 38.73802 48.88341 36.42487 51.98774
## Mar 1950       46.32380 41.23123 52.04536 38.76609 55.35493
## Apr 1950       47.54102 42.31462 53.41295 39.78470 56.80950
## May 1950       54.30774 48.33735 61.01557 45.44729 64.89565
## Jun 1950       61.84802 55.04866 69.48721 51.75732 73.90602
## Jul 1950       59.98829 53.39338 67.39777 50.20101 71.68371
## Aug 1950       62.06182 55.23896 69.72742 51.93624 74.16150
## Sep 1950       59.63140 53.07574 66.99679 49.90237 71.25722
## Oct 1950       50.33309 44.79965 56.54998 42.12111 60.14608
## Nov 1950       48.90337 43.52794 54.94264 40.92583 58.43594
## Dec 1950       39.34859 35.02600 44.20464 32.93344 47.01337
## Jan 1951       42.77795 37.78161 48.43503 35.37746 51.72654
## Feb 1951       44.00356 38.83869 49.85526 36.35470 53.26170
## Mar 1951       46.72959 41.23791 52.95261 38.59708 56.57566
## Apr 1951       47.60582 42.01114 53.94555 39.32078 57.63655
## May 1951       54.49657 48.09198 61.75409 45.01215 65.97944
## Jun 1951       62.03905 54.74802 70.30106 51.24193 75.11122
## Jul 1951       59.74523 52.72378 67.70176 49.34732 72.33407
## Aug 1951       61.95682 54.67546 70.20788 51.17402 75.01166
## Sep 1951       59.74774 52.72601 67.70458 49.34941 72.33707
## Oct 1951       50.43346 44.50637 57.14987 41.65617 61.06019
## Nov 1951       49.29126 43.49934 55.85437 40.71409 59.67537
## Dec 1951       39.36663 34.74380 44.60454 32.52061 47.65382
## Jan 1952       43.11907 37.73393 49.27274 35.16106 52.87822
## Feb 1952       44.49500 38.91033 50.88120 36.24360 54.62495
## Mar 1952       47.14199 41.21764 53.91786 38.38910 57.89058
## Apr 1952       47.66941 41.67875 54.52112 38.81855 58.53831
## May 1952       54.68611 47.81355 62.54652 44.53229 67.15511
## Jun 1952       62.23263 54.41165 71.17777 50.67758 76.42235
## Jul 1952       59.50356 52.02556 68.05644 48.45524 73.07103
## Aug 1952       61.85196 54.07882 70.74238 50.36759 75.95488
## Sep 1952       59.86371 52.34046 68.46833 48.74854 73.51326
## Oct 1952       50.53828 44.18699 57.80249 41.15461 62.06153
## Nov 1952       49.68204 43.43939 56.82182 40.45882 61.00783
## Dec 1952       39.38642 34.44065 45.04242 32.07911 48.35826
## Jan 1953       43.46210 37.66138 50.15627 34.91096 54.10776
## Feb 1953       44.99289 38.95809 51.96250 36.09838 56.07896
## Mar 1953       47.55649 41.16985 54.93388 38.14387 59.29183
## Apr 1953       47.73380 41.32332 55.13873 38.28604 59.51296
## May 1953       54.87629 47.50648 63.38941 44.01468 68.41826
## Jun 1953       62.42569 54.04198 72.10999 50.06980 77.83068
## Jul 1953       59.26254 51.30364 68.45613 47.53273 73.88696
## Aug 1953       61.74720 53.45461 71.32624 49.52561 76.98475
## Sep 1953       59.98020 51.92494 69.28509 48.10837 74.78166
## Oct 1953       50.64099 43.83998 58.49706 40.61767 63.13779
## Nov 1953       50.07614 43.35212 57.84307 40.16622 62.43106
## Dec 1953       39.40524 34.11756 45.51244 31.61201 49.11972
## Jan 1954       43.80833 37.56636 51.08746 34.63058 55.41836
## Feb 1954       45.49589 38.98172 53.09863 35.91985 57.62485
## Mar 1954       47.97552 41.09780 56.00422 37.86557 60.78478
## Apr 1954       47.79791 40.94563 55.79692 37.72535 60.55981
## May 1954       55.06715 47.17262 64.28286 43.46254 69.77022
## Jun 1954       62.61992 53.64259 73.09964 49.42364 79.33964
## Jul 1954       59.02262 50.56101 68.90032 46.58443 74.78186
## Aug 1954       61.64261 52.80539 71.95877 48.65229 78.10138
## Sep 1954       60.09674 51.48117 70.15417 47.43222 76.14272
## Oct 1954       50.74513 43.47022 59.23753 40.05133 64.29420
## Nov 1954       50.47330 43.23859 58.91854 39.83851 63.94702
## Dec 1954       39.42458 33.77731 46.01602 31.12305 49.94039
## Jan 1955       44.15708 37.45023 52.06504 34.32262 56.80941
## Feb 1955       46.00480 38.98373 54.29037 35.71177 59.26453
## Mar 1955       48.39779 41.00253 57.12685 37.55678 62.36812
## Apr 1955       47.86231 40.54885 56.49484 37.14121 61.67814
## May 1955       55.25867 46.81489 65.22541 42.88060 71.20983
## Jun 1955       62.81443 53.21607 74.14400 48.74382 80.94672
## Jul 1955       58.78358 49.80116 69.38612 45.61589 75.75231
## Aug 1955       61.53818 52.13485 72.63756 47.75346 79.30206
## Sep 1955       60.21360 51.01269 71.07403 46.72562 77.59507
## Oct 1955       50.84882 43.07889 60.02017 39.45857 65.52701
## Nov 1955       50.87368 43.10126 60.04768 39.47970 65.55599
## Dec 1955       39.44365 33.42148 46.55093 30.61519 50.81795
## Jan 1956       44.50875 37.31473 53.08972 33.98985 58.28295
## Feb 1956       46.51926 38.96498 55.53811 35.47605 61.00007
## Mar 1956       48.82403 40.88606 58.30313 37.22058 64.04483
## Apr 1956       47.92669 40.13458 57.23162 36.53645 62.86782
## May 1956       55.45085 46.43530 66.21680 42.27223 72.73799
## Jun 1956       63.00971 52.76516 75.24327 48.03459 82.65342
## Jul 1956       58.54554 49.02681 69.91237 44.63140 76.79752
## Aug 1956       61.43393 51.44559 73.36154 46.83332 80.58638
## Sep 1956       60.33063 50.52170 72.04401 45.99227 79.13907
## Oct 1956       50.95307 42.66880 60.84575 38.84341 66.83798
## Nov 1956       51.27721 42.94163 61.23084 39.09245 67.25984
## Dec 1956       39.46287 33.05202 47.11718 30.09135 51.75301
## Jan 1957       44.86315 37.16116 54.16144 33.63463 59.84017
## Feb 1957       47.03955 38.92703 56.84276 35.21526 62.83412
## Mar 1957       49.25389 40.74965 59.53291 36.85939 65.81621
## Apr 1957       47.99121 39.70496 58.00677 35.91441 64.12902
## May 1957       55.64370 46.03601 67.25652 41.64098 74.35516
## Jun 1957       63.20550 52.29213 76.39650 47.29982 84.45984
## Jul 1957       58.30845 48.24062 70.47743 43.63511 77.91604
## Aug 1957       61.32985 50.74034 74.12939 45.89618 81.95345
## Sep 1957       60.44792 50.01071 73.06337 45.23622 80.77490
## Oct 1957       51.05734 42.24156 61.71298 38.20879 68.22651
## Nov 1957       51.68395 42.76144 62.46822 38.67974 69.06021
## Dec 1957       39.48202 32.67040 47.71383 29.55402 52.74509
\end{verbatim}

Based on this result, we can see that both models predict well, but the
first model has a smaller AIC.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{car\_sale}\OtherTok{\textless{}{-}}\FunctionTok{read.csv}\NormalTok{(}\StringTok{"./Datasets{-}master/monthly{-}car{-}sales.csv"}\NormalTok{)}
\NormalTok{MyData1 }\OtherTok{\textless{}{-}}\NormalTok{ car\_sale}\SpecialCharTok{$}\NormalTok{Sales}
\NormalTok{tsdata1 }\OtherTok{\textless{}{-}} \FunctionTok{ts}\NormalTok{(MyData1, }\AttributeTok{start =}\FunctionTok{c}\NormalTok{(}\DecValTok{1960}\NormalTok{,}\DecValTok{1}\NormalTok{),}\AttributeTok{frequency =} \DecValTok{12}\NormalTok{)}
\FunctionTok{plot.ts}\NormalTok{(tsdata1)}
\end{Highlighting}
\end{Shaded}

\includegraphics{in_work2_files/figure-latex/unnamed-chunk-17-1.pdf}
Monthly car sales receive seasonal influences and are seasonal in nature
and increase from year to year.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{acf}\NormalTok{(MyData1)}
\end{Highlighting}
\end{Shaded}

\includegraphics{in_work2_files/figure-latex/unnamed-chunk-18-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{pacf}\NormalTok{(MyData1)}
\end{Highlighting}
\end{Shaded}

\includegraphics{in_work2_files/figure-latex/unnamed-chunk-19-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(}\FunctionTok{decompose}\NormalTok{(tsdata1,}\AttributeTok{type =} \StringTok{"additive"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{in_work2_files/figure-latex/unnamed-chunk-20-1.pdf} I
used the decompose function to find the seasonal component , and from
the ACF plot, we can see at lag=12, the ACF is very high, so the length
of seasonality is 12. From the image, the fluctuation of the sequence
grows with the overall level.Seasonally, cars are sold a little more in
the summer.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{  fit\_model1 }\OtherTok{\textless{}{-}} \FunctionTok{Arima}\NormalTok{(tsdata1,}\AttributeTok{order=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{0}\NormalTok{,}\DecValTok{2}\NormalTok{),}\AttributeTok{seasonal=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{),}\AttributeTok{lambda=}\DecValTok{0}\NormalTok{)}
  \FunctionTok{summary}\NormalTok{(fit\_model1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Series: tsdata1 
## ARIMA(1,0,2)(1,1,2)[12] 
## Box Cox transformation: lambda= 0 
## 
## Coefficients:
##          ar1      ma1      ma2     sar1    sma1     sma2
##       0.9963  -0.7197  -0.1361  -0.7699  0.2483  -0.5298
## s.e.  0.0070   0.0995   0.0964   0.5333  0.5635   0.2878
## 
## sigma^2 estimated as 0.01349:  log likelihood=70.33
## AIC=-126.66   AICc=-125.39   BIC=-108.71
## 
## Training set error measures:
##                    ME     RMSE      MAE        MPE     MAPE      MASE
## Training set 9.354931 1502.209 1150.736 -0.1175816 7.973636 0.7214551
##                    ACF1
## Training set 0.06200981
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fit\_model1.residuals }\OtherTok{\textless{}{-}} \FunctionTok{residuals}\NormalTok{(fit\_model)}
\FunctionTok{shapiro.test}\NormalTok{(fit\_model1.residuals)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Shapiro-Wilk normality test
## 
## data:  fit_model1.residuals
## W = 0.99441, p-value = 0.5232
\end{verbatim}

I used the Shapiro test to check the disrtibution of errors of the
ARIMA(1,0,2)(1,1,2){[}12{]} model, the p-calue=0.3176 \textgreater{}
0.05 , so we couldn't reject the H0, that means the error has normal
distribution.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{  fit\_model }\OtherTok{\textless{}{-}} \FunctionTok{Arima}\NormalTok{(tsdata1,}\AttributeTok{order=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{),}\AttributeTok{lambda=}\DecValTok{0}\NormalTok{)}
  \FunctionTok{summary}\NormalTok{(fit\_model)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Series: tsdata1 
## ARIMA(1,1,2) 
## Box Cox transformation: lambda= 0 
## 
## Coefficients:
##          ar1      ma1      ma2
##       0.4456  -0.5835  -0.3298
## s.e.  0.1250   0.1151   0.1004
## 
## sigma^2 estimated as 0.0462:  log likelihood=13.66
## AIC=-19.32   AICc=-18.92   BIC=-8.63
## 
## Training set error measures:
##                    ME    RMSE     MAE      MPE     MAPE     MASE      ACF1
## Training set 721.7876 3017.43 2330.59 1.676636 16.08661 1.461166 0.0475897
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fit\_autochose }\OtherTok{\textless{}{-}} \FunctionTok{auto.arima}\NormalTok{(tsdata1,}\AttributeTok{seasonal =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{ic =} \StringTok{"aic"}\NormalTok{,}\AttributeTok{D=}\DecValTok{1}\NormalTok{)}
\FunctionTok{summary}\NormalTok{(fit\_autochose)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Series: tsdata1 
## ARIMA(1,0,1)(0,1,1)[12] with drift 
## 
## Coefficients:
##          ar1      ma1     sma1    drift
##       0.7663  -0.5394  -0.5619  83.3957
## s.e.  0.1685   0.2208   0.1337  12.8709
## 
## sigma^2 estimated as 2328583:  log likelihood=-840.23
## AIC=1690.45   AICc=1691.12   BIC=1703.27
## 
## Training set error measures:
##                    ME     RMSE      MAE        MPE     MAPE      MASE
## Training set 15.74514 1408.406 1076.439 -0.9011266 7.535356 0.6748744
##                     ACF1
## Training set -0.01349078
\end{verbatim}

Based on the RMSE and MAE, our best model in this case is
ARIMA(1,0,1)(0,1,1){[}12{]}.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{checkresiduals}\NormalTok{(fit\_autochose)}
\end{Highlighting}
\end{Shaded}

\includegraphics{in_work2_files/figure-latex/unnamed-chunk-25-1.pdf}

\begin{verbatim}
## 
##  Ljung-Box test
## 
## data:  Residuals from ARIMA(1,0,1)(0,1,1)[12] with drift
## Q* = 26.969, df = 18, p-value = 0.07957
## 
## Model df: 4.   Total lags used: 22
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fit\_autochose.residuals }\OtherTok{\textless{}{-}} \FunctionTok{residuals}\NormalTok{(fit\_autochose)}
\NormalTok{fit\_autochose.fitted }\OtherTok{\textless{}{-}}\NormalTok{ tsdata1 }\SpecialCharTok{{-}}\NormalTok{ fit\_autochose.residuals}
\FunctionTok{ts.plot}\NormalTok{(tsdata1)}
\FunctionTok{points}\NormalTok{(fit\_autochose.fitted, }\AttributeTok{type =} \StringTok{"l"}\NormalTok{, }\AttributeTok{col =} \DecValTok{2}\NormalTok{, }\AttributeTok{lty =} \DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{in_work2_files/figure-latex/unnamed-chunk-26-1.pdf} Use
the best model to forecast 2 years ahead

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{autoplot}\NormalTok{(}\FunctionTok{forecast}\NormalTok{(fit\_autochose,}\AttributeTok{h=}\DecValTok{24}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{in_work2_files/figure-latex/unnamed-chunk-27-1.pdf}

\end{document}
